# Generated by Django 5.0.3 on 2024-03-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='star_cast',
        ),
    ]
